options:
  check_ports:
    default: '31337' 
    description: Comma separated list of ports to test on peers
    type: string 
  check_list:
    default: ''
    description: |
        Comma separated list of label:host:port or label:host:port:send:receive
        e.g. google:www.google.com:80, ubuntu_ftp:ftp.ubuntu.com:21
        e.g. google_http:www.google.com:80:get /:302
        e.g. ubuntu_ftp:ftp.ubuntu.com:21:test:503 
    type: string
